USE TEST;

# CREATE TABLES- SYSTEMS, ACCOUNTS
CREATE TABLE SYSTEMS(
 SYS_ID INTEGER PRIMARY KEY, 
 SYS_NAME VARCHAR(50)
);

CREATE TABLE ACCOUNTS(
 SYS_ID INTEGER, 
 ID VARCHAR(255) PRIMARY KEY, 
 PASSWORD INTEGER
);

# INSERT INTO DATABASE- SYSTEMS
INSERT INTO SYSTEMS 
VALUES(1, "SECURITY"), 
(2, "INTERSECTION");

INSERT INTO SYSTEMS 
VALUES(3, "SCHOOLZONE"), (4, "LEFT_TURN");

# INSERT INTO DATABASE- ACCOUNTS
-- INSERT INTO ACCOUNTS VALUES(WRONG QUERY)
-- (1, "SEC", 1234), (2, "ITS", 1234), (3, "SCH", 1234), (4, "LFT", 1234)
-- SELECT A.SYS_ID, A.ID, A.PASSWORD 
-- FROM ACCOUNTS A, SYSTEMS S
-- WHERE A.SYS_ID = S.SYS_ID;

-- RIGHT QUERY
INSERT INTO ACCOUNTS (SYS_ID, ID, PASSWORD)
SELECT S.SYS_ID, 'new_id', 1234 
FROM SYSTEMS S
WHERE S.SYS_ID = 1;

INSERT INTO ACCOUNTS VALUES 
(1, "SEC", 1234), (2, "ITS", 1234), (3, "SCH", 1234), (4, "LFT", 1234);
-- INSERT INTO ACCOUNTS VALUES (1, "SECURITY", 1234);

-- SELECT TO SEE THE DATAS
SELECT * FROM ACCOUNTS
ORDER BY SYS_ID;


SELECT * FROM SYSTEMS;

SELECT S.SYS_ID, A.ID, a.password
FROM ACCOUNTS a, SYSTEMS s
WHERE A.SYS_ID =S.SYS_ID
ORDER BY S.SYS_ID ;

SELECT COUNT(ID) FROM ACCOUNTS;

SELECT S.SYS_ID, A.ID, A.PASSWORD
FROM ACCOUNTS A, SYSTEMS S
WHERE S.SYS_ID= A.SYS_ID
ORDER BY A.SYS_ID ASC ;

-- DELETE DATAS IN TABLES
DELETE FROM SYSTEMS;
DELETE FROM ACCOUNTS;

-- DELETE TABLES
DROP TABLE SYSTEMS;
DROP TABLE ACCOUNTS;

--  GENERATE TESTING ACCOUNTS
INSERT INTO ACCOUNTS(SYS_ID, ID) VALUES 
(1, "SECURITY"), 
(1, "CCTV"), 
(2, "ITS"), 
(2, "INTERSECTION"), 
(2, "INTSEC"), 

(3, "SCH"), 
(3, "SCHOOLZONE"), 
(3, "SZONE"), 

(4, "LFT"), 
(4, "LEFT_TURN"), 
(4, "LTURN"),